### ISSUE TITLE
Add `DEVELOPMENT.md`

### ISSUE THREAD

**Issue by ctreatma** [equinix-labs/metal-python#3]
Add a `DEVELOPMENT.md` doc that guides a user through the process of installing any prerequisites and setting up their environment for local development.

The Equinix terraform provider has a good example of what should go in this doc: https://github.com/equinix/terraform-provider-equinix/blob/master/DEVELOPMENT.md

**Comment by displague** [comment]
We'll also need documentation on how to cut releases (automated or not). https://github.com/packethost/packet-python/blob/master/RELEASE.md is an example of that. This could be included in the DEVELOPMENT.md or kept separate.

**Comment by ctreatma** [comment]
I think we should have a `DEVELOPMENT.md` in all of our repos to document prerequisites, setup steps, etc. (I opened this issue because it took me a minute to figure out what dependencies to install in order to build this SDK).  Those files don't exist in `metal-java` or `metal-go` yet, but they should exist there as well.  In the case of `metal-go`, there's a similar issue to add that doc, and `metal-java` has development setup steps in the top-level README.md (not the best place for it IMO, but the most important thing is having it documented).

**Comment by t0mk** [comment]
@ctreatma I'll do DEVELOPMENT.md then. It's now necessary to use a custom build of openapi-generator-cli to build the SDK because of some reported bugs (in the generator), but that should be resolved in a couple of weeks at most.

for example https://github.com/OpenAPITools/openapi-generator/pull/14809
