### ISSUE TITLE
Support for Python asyncio

### ISSUE THREAD

**Issue by marcoceppi** [equinix-labs/metal-python#36]
It'd be great if support for asyncio was added to this library vs the current "async" implementation of threadpools. It would allow for integration into existing asyncio projects. While I understand the OpenAPI generator used [supports AsyncIO](https://openapi-generator.tech/docs/generators/python/#config-options) as a library for generation, I'm also aware it's a one-or-nothing approach and doesn't do well to put sync and async side-by-side.

In the past to get around this I've used https://github.com/openapi-generators/openapi-python-client which similar in approach supports both sync and asyncio out of the box. The rendered library will be distinctly different but the openapi-python-client allows for template level overrides (with Jinja) that could be leveraged to keep the general interface in-line and minimize breaking changes.

**Comment by t0mk** [comment]
hi @marcoceppi, thanks for your interest in the project. Can I ask what you want to use it for?

This (https://github.com/equinix-labs/metal-python/issues/38) will need to happen first, but then I'm happy to explore how to generate asyncio code :).

**Comment by t0mk** [comment]
@marcoceppi I tried to generate code with the latest openapi-generator-cli, python generator, and `--library asyncio` and the difference seems to be that if I generate with asyncio, there are always 2 functions for an API method, for example:
```
@overload
async def find_plans(..

@overload
def find_plans(..
```

When I generate with `--library urillib3`, there's only the (2nd) sync version. In other words, the asyncio version of the generated code seems compatible with the urllib3 version (used currently). I would need to verify in the Ansible collection, but it looks like we could just generate with `--library asyncio`, and it wouldn't be a breaking change.

**Comment by t0mk** [comment]
Code generated with `--library asyncio` will probably not work anymore since we're using templates.
